const now = new Date().toJSON()

const logs = [
    {
        'id': 167,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '7b8673d5-d70d-4634-ad44-ffa9ac78a180',
        'duration': 6,
        'reqLength': 54,
        'resLength': 14837,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 166,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '350c0ced-85fd-4ccf-b780-2880b4bffa56',
        'duration': 3,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 165,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '1f7e3c7c-a537-4c26-91e0-383b9b147cd0',
        'duration': 6,
        'reqLength': 54,
        'resLength': 14840,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 164,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '77d6bfd9-dac1-441d-90f3-eb54fc4938fd',
        'duration': 5,
        'reqLength': 54,
        'resLength': 9115,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 163,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '9fe72cde-99c7-4685-9f91-4c8b2b7c2ad0',
        'duration': 8,
        'reqLength': 54,
        'resLength': 14840,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 162,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'f6340cdf-8da5-4d39-93e5-5876e684e9b7',
        'duration': 12,
        'reqLength': 54,
        'resLength': 14840,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 161,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '5f324e4c-6d7a-496a-a2d0-f013e3d02fcb',
        'duration': 6,
        'reqLength': 54,
        'resLength': 9115,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 160,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'ade76c01-d95f-41cd-a676-a2de7396892c',
        'duration': 5,
        'reqLength': 54,
        'resLength': 9115,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 159,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '46704de7-f705-4f76-b7f3-9befd5b8231b',
        'duration': 8,
        'reqLength': 54,
        'resLength': 9115,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 158,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '7f813ffb-348e-4254-9d09-c833295ab7bb',
        'duration': 8,
        'reqLength': 54,
        'resLength': 9115,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 157,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'd1d7b52a-f98d-49b3-bac3-296e0f08d3af',
        'duration': 3,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 156,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '42c999f2-a8dd-4cce-9a83-c135b9b26cda',
        'duration': 11,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 155,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '82484344-7dd6-47ba-933c-24b68a270cb7',
        'duration': 7,
        'reqLength': 41,
        'resLength': 1,
        'module': 'rule',
        'func': 'del',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 154,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '06a1dd54-0122-4fac-9986-ca2c4456662a',
        'duration': 4,
        'reqLength': 40,
        'resLength': 960,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 153,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '6d77f6e7-bb02-4af4-8be6-62c6d698730e',
        'duration': 4,
        'reqLength': 40,
        'resLength': 960,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 152,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '0ca35be1-c8a0-4d50-914d-42807d7f7588',
        'duration': 9,
        'reqLength': 407,
        'resLength': 465,
        'module': 'rule',
        'func': 'add',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 151,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'a3c36a92-9195-459d-b277-61cac365aa5f',
        'duration': 5,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 150,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '80c9dda4-784e-4432-853d-596dda6b7a93',
        'duration': 3,
        'reqLength': 42,
        'resLength': 101,
        'module': 'user',
        'func': 'login',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 149,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '7f819e0a-6667-48f4-babd-73e809473796',
        'duration': 71,
        'reqLength': 57,
        'resLength': 171,
        'module': 'user',
        'func': 'login',
        'user': 'admin',
        'authType': 'basic',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 148,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '5c65cc69-c59a-4a06-bb78-021d77abfa5b',
        'duration': 6,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 147,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': 'd3bf38c5-83b2-4eca-9507-b1737d74d58e',
        'duration': 5,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 146,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '6de4aa85-0daa-4af4-b7a4-a95b638952ae',
        'duration': 3,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 145,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '35e4d77c-413d-41a8-b22e-2d2d4f093048',
        'duration': 28,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 144,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '69de210b-680d-4d66-a357-056f08c05f5e',
        'duration': 11,
        'reqLength': 40,
        'resLength': 0,
        'module': 'rule',
        'func': 'get',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 143,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '37e9a863-7870-495f-8756-4a8b81b1280e',
        'duration': 3,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 142,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '10e6edb9-33d7-4a6b-8b9a-394ecc530101',
        'duration': 20,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 141,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '4448234f-5e31-4e82-8512-9b3e2580b1fc',
        'duration': 4,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 140,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '435c6b5d-cc6a-46c4-94ba-59cb0542108b',
        'duration': 3,
        'reqLength': 42,
        'resLength': 101,
        'module': 'user',
        'func': 'login',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 139,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '3a3266a0-5314-44dc-a006-f38c439550e8',
        'duration': 3,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 138,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'ccba6da6-fd9c-4645-ab0a-2a49ba5e7df7',
        'duration': 4,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 137,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '76534420-2dff-4e1f-870d-0bfcfea8d06f',
        'duration': 5,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 136,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '4a5fe75d-8e45-4c87-a7b4-6e950aa97b9e',
        'duration': 6,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 135,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'c995b93a-0b8b-41fa-babb-f2787dc79b4d',
        'duration': 4,
        'reqLength': 42,
        'resLength': 101,
        'module': 'user',
        'func': 'login',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 134,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '9be10029-e3bc-46d7-9539-84ace62c4677',
        'duration': 83,
        'reqLength': 57,
        'resLength': 171,
        'module': 'user',
        'func': 'login',
        'user': 'admin',
        'authType': 'basic',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 133,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '3db57d0a-9b30-4ab6-9b51-1fc8d4d779c1',
        'duration': 2,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 132,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '18b82485-3909-41c6-b684-287ed65f6a6d',
        'duration': 2,
        'reqLength': 40,
        'resLength': 0,
        'module': 'rule',
        'func': 'get',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 131,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': 'ce1be36c-49ff-4108-af2e-6b219ec5fac5',
        'duration': 4,
        'reqLength': 42,
        'resLength': 0,
        'module': 'user',
        'func': 'login',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 130,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 401,
        'transaction': '30bec098-1d64-4c82-bafa-daf3c0bf1c7e',
        'duration': 76,
        'reqLength': 40,
        'resLength': 0,
        'module': 'rule',
        'func': 'get',
        'user': null,
        'authType': null,
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 129,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'd28de329-8cd6-4d62-8297-8aa1809f7a3a',
        'duration': 13,
        'reqLength': 56,
        'resLength': 40385,
        'module': 'proxylog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 128,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '203625a5-2d20-471f-b3d7-4edd5dced2fc',
        'duration': 3,
        'reqLength': 40,
        'resLength': 494,
        'module': 'rule',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 127,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'afc15ddd-9909-4610-ab13-d0b391bdb716',
        'duration': 6,
        'reqLength': 54,
        'resLength': 14917,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 126,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'fcd07aec-a5d3-44a5-afb4-4a29643a4b9f',
        'duration': 4,
        'reqLength': 54,
        'resLength': 4165,
        'module': 'syslog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 125,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '044979e9-ec55-43fd-834c-96e866957588',
        'duration': 12,
        'reqLength': 43,
        'resLength': 275,
        'module': 'project',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 124,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': 'e66572e0-abf1-4458-9129-be89f04ad69f',
        'duration': 15,
        'reqLength': 38,
        'resLength': 6003,
        'module': 'pm',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 123,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '9d79cf23-97b4-4144-94fb-2e2c5edd52e3',
        'duration': 4,
        'reqLength': 58,
        'resLength': 406,
        'module': 'projectlog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 122,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '5e4dd6e4-7b21-440c-be47-2017c8804adf',
        'duration': 15,
        'reqLength': 43,
        'resLength': 275,
        'module': 'project',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 121,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '79eb021a-4c3c-4524-98c7-f03168791f24',
        'duration': 6,
        'reqLength': 54,
        'resLength': 12453,
        'module': 'joblog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 120,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '0b80db37-1310-43a5-9e45-a7a95fce9eaf',
        'duration': 3,
        'reqLength': 39,
        'resLength': 455,
        'module': 'job',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 119,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '3cba69e1-2381-40ea-b091-567db9e3523c',
        'duration': 6,
        'reqLength': 54,
        'resLength': 12453,
        'module': 'joblog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    },
    {
        'id': 118,
        'url': '/api/rpc',
        'method': 'POST',
        'status': 200,
        'transaction': '8fc365f0-d772-4da3-8510-b145b84b8c4a',
        'duration': 7,
        'reqLength': 54,
        'resLength': 14888,
        'module': 'apilog',
        'func': 'get',
        'user': 'admin',
        'authType': 'bearer',
        'createdAt': now,
        'updatedAt': now
    }
]

const get = (timerange, keyword, offset, limit) => {
    let lg = [...logs]
    if (timerange) {
        lg = lg.filter(
            item =>
                new Date(item.createdAt) >= new Date(timerange[0]) &&
                new Date(item.createdAt) <= new Date(timerange[1])
        )
    }
    if (keyword) {
        keyword = keyword.toLowerCase()
        lg = lg.filter(
            item =>
                item.transaction?.toLowerCase()?.includes(keyword) ||
                item.module?.toLowerCase()?.includes(keyword) ||
                item.func?.toLowerCase()?.includes(keyword) ||
                item.user?.toLowerCase()?.includes(keyword) ||
                item.authType?.toString()?.includes(keyword)
        )
    }
    const count = lg.length
    return {
        data: lg.slice(offset, offset + limit),
        count
    }
}

const clear = () => {
    logs.splice(0, logs.length)
}

export default {
    get,
    clear
}
