const now = new Date().toJSON()

const logs = [
    {
        'id': 420,
        'url': '/api/folder?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'GET',
        'status': 200,
        'transaction': '1d8647aa-0258-4717-97af-dec6cb3d7026',
        'duration': 28,
        'reqLength': 0,
        'resLength': 1474,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 419,
        'url': '/api/del-file',
        'method': 'POST',
        'status': 200,
        'transaction': 'fc2c83da-4f63-49ff-adda-b40f8e8de78c',
        'duration': 18,
        'reqLength': 377,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 418,
        'url': '/api/folder?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'GET',
        'status': 200,
        'transaction': 'f76f8b67-9146-4d8b-893d-a1c3caa473d2',
        'duration': 217,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 417,
        'url': '/static/source/js/ionic/svg/cloud-download-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '5e6a3302-96f5-4952-ad1a-228b1d14950b',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 416,
        'url': '/static/source/js/ionic/svg/cut-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': 'cfbc3a0c-11f5-4733-99ff-f4bd45b67578',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 415,
        'url': '/static/source/js/ionic/svg/pencil-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '3ce07e1e-5108-4081-b17c-744fe1c67949',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 414,
        'url': '/static/source/js/ionic/svg/share-social-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '534edf24-2a6a-4944-ba58-e6b0e8fd844a',
        'duration': 17,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 413,
        'url': '/static/source/js/ionic/p-71492a83.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '5aa9e63d-7b53-43ed-9da4-320bb2519f73',
        'duration': 211,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 412,
        'url': '/api/folder?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'GET',
        'status': 200,
        'transaction': '6917aa48-7992-473e-aef7-252c17d5ffa1',
        'duration': 39,
        'reqLength': 0,
        'resLength': 1526,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 411,
        'url': '/api/file/upload?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'POST',
        'status': 200,
        'transaction': '5ab00fd2-6bc7-489a-ba9b-47a768c0038f',
        'duration': 146,
        'reqLength': 1303,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 410,
        'url': '/static/source/js/ionic/p-fb21cfbd.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '5e2afb86-097a-4c82-9646-368cb48cc80a',
        'duration': 124,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 409,
        'url': '/static/source/js/ionic/p-640995d1.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '18e25d19-766b-4f4c-b765-a40290d2f6c1',
        'duration': 17,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 408,
        'url': '/api/folder?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'GET',
        'status': 200,
        'transaction': '6860a21c-78ab-4bca-b385-25c6695b1dad',
        'duration': 33,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 407,
        'url': '/static/source/assets/html.png',
        'method': 'GET',
        'status': 200,
        'transaction': '479a0edd-3f75-4406-b88d-d22830d2feb0',
        'duration': 16,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 406,
        'url': '/static/source/assets/unknown.png',
        'method': 'GET',
        'status': 200,
        'transaction': 'f3a7550e-c759-4676-8251-e15e47c4d3e9',
        'duration': 18,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 405,
        'url': '/static/source/assets/pdf.png',
        'method': 'GET',
        'status': 200,
        'transaction': 'e68aef13-071c-4b47-a555-8c57b656c973',
        'duration': 15,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 404,
        'url': '/static/source/assets/mp4.png',
        'method': 'GET',
        'status': 200,
        'transaction': 'fc9b5fc7-4547-497f-af40-2bee4f805d2b',
        'duration': 25,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 403,
        'url': '/static/source/assets/excel.png',
        'method': 'GET',
        'status': 200,
        'transaction': 'e65c1c7c-ad7d-4ca6-8b13-4c1ff5bba4f6',
        'duration': 23,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 402,
        'url': '/static/source/assets/txt.png',
        'method': 'GET',
        'status': 200,
        'transaction': '99cbfbf6-41e8-4161-b22c-ad3fd464c3da',
        'duration': 21,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 401,
        'url': '/static/source/assets/jpg.png',
        'method': 'GET',
        'status': 200,
        'transaction': '76620f42-caae-4f11-8b5e-cce8d0074ef8',
        'duration': 21,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 400,
        'url': '/static/source/assets/doc.png',
        'method': 'GET',
        'status': 200,
        'transaction': '9f91a953-de04-4e9a-95d7-feb18a910910',
        'duration': 20,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 399,
        'url': '/static/source/assets/folder.png',
        'method': 'GET',
        'status': 200,
        'transaction': 'e44c9f9b-63ea-4b42-a581-3c30312c6e29',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 398,
        'url': '/static/source/js/ionic/p-d02f7564.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': 'f4208bf9-f401-41f1-a3f9-521185b79f4d',
        'duration': 13,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 397,
        'url': '/api/folder?path=C%3A%5CUsers%5CNeko%20Gong%5C%u5B66%u4E60%5Cshare-my-file%5Cpublic%5Cdata',
        'method': 'GET',
        'status': 200,
        'transaction': '9026afcd-03d0-4e4e-b1c2-6b7162f75085',
        'duration': 47,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 396,
        'url': '/static/source/js/ionic/svg/close.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '3257b00d-b7f0-4692-b93d-90d5f169014a',
        'duration': 14,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 395,
        'url': '/api/fav',
        'method': 'GET',
        'status': 200,
        'transaction': '311dc8e5-0074-497b-aeea-efbc022152e9',
        'duration': 15,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 394,
        'url': '/api/sep',
        'method': 'GET',
        'status': 200,
        'transaction': 'a98dda3f-4945-471f-a5ea-e6cb7d270d78',
        'duration': 12,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 393,
        'url': '/static/source/js/ionic/p-5abed003.js',
        'method': 'GET',
        'status': 200,
        'transaction': 'c8f894b1-5e6c-4a29-8db7-860e636ce330',
        'duration': 22,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 392,
        'url': '/static/source/js/ionic/p-1176c85c.js',
        'method': 'GET',
        'status': 200,
        'transaction': '567e687b-af2c-449b-a0ae-9603eb764516',
        'duration': 22,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 391,
        'url': '/api/hostname',
        'method': 'GET',
        'status': 200,
        'transaction': 'b8ad891d-ee40-4b67-b8b9-6d96e4086d8e',
        'duration': 22,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 390,
        'url': '/static/source/js/ionic/svg/hardware-chip-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '4896c442-448a-40c4-8842-0347fe97d463',
        'duration': 17,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 389,
        'url': '/static/source/js/ionic/p-654ec3a6.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '1fac4524-3eb4-44da-8f48-6865ab6bbbf3',
        'duration': 18,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 387,
        'url': '/static/source/js/ionic/svg/file-tray-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '6ee8f433-580f-4782-894f-5f87dfb42b0f',
        'duration': 18,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 388,
        'url': '/static/source/js/ionic/svg/refresh-circle-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '372df9c7-26b7-45f8-bdf0-1cd34bb7d50b',
        'duration': 18,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 386,
        'url': '/static/source/js/ionic/p-da2d88c1.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': 'fd87de85-b284-43d4-af3d-0b951aa9738d',
        'duration': 23,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 385,
        'url': '/api/win',
        'method': 'GET',
        'status': 200,
        'transaction': '5d05a5c3-6ff0-4195-8c72-d7c30a886529',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 384,
        'url': '/static/source/js/ionic/svg/laptop-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': 'c85c8d79-d9a5-4875-8029-79321b62c765',
        'duration': 16,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 383,
        'url': '/static/source/js/ionic/p-bd428743.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '7839feac-9407-43ff-82e8-7712a4dabd8c',
        'duration': 14,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 382,
        'url': '/static/source/js/ionic/svg/checkbox-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '6bcbf4c9-bbb7-408e-a294-265ecfb22b54',
        'duration': 22,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 381,
        'url': '/static/source/js/ionic/p-7b37e8fe.entry.js',
        'method': 'GET',
        'status': 200,
        'transaction': '0215b381-a386-4702-abdb-47b7fc7059f6',
        'duration': 21,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 379,
        'url': '/static/source/js/ionic/svg/cloud-upload-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '6ba0db81-9f4c-4adf-a988-01bd386dd654',
        'duration': 21,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 380,
        'url': '/static/source/js/ionic/svg/create-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '93cb7a68-79b5-4a43-8db3-206db6e44ca1',
        'duration': 22,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 378,
        'url': '/static/source/js/ionic/svg/chevron-back-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '365bf0a3-9339-48d4-a39c-abef1c85f4be',
        'duration': 25,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 377,
        'url': '/static/source/js/ionic/svg/documents-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '5943d1d6-71b0-4226-b415-e1fba3843ce3',
        'duration': 24,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 376,
        'url': '/static/source/js/ionic/svg/add.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '9c35d03f-b25e-4d8c-bba0-b54b045f3ad1',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 375,
        'url': '/static/source/js/ionic/svg/funnel-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '3e57e79f-a8ae-4d09-9bd6-62bbc8e3569b',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 374,
        'url': '/static/source/js/ionic/svg/trash-bin-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '16734203-7ce7-4fb9-9ac4-a0b251f8c1f0',
        'duration': 21,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 373,
        'url': '/static/source/js/ionic/svg/attach-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '8fa496a7-daf1-4a2e-941d-dd92279890fd',
        'duration': 19,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 372,
        'url': '/static/source/js/ionic/svg/copy-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': 'ceed0c8f-c9a9-4bff-9708-5344e450eaad',
        'duration': 18,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    },
    {
        'id': 371,
        'url': '/static/source/js/ionic/svg/reload-outline.svg',
        'method': 'GET',
        'status': 200,
        'transaction': '74b7e3a8-4021-45e4-a252-cf9dcd3d9f27',
        'duration': 110,
        'reqLength': 0,
        'resLength': 0,
        'ruleName': 'Share my file',
        'createdAt': now,
        'updatedAt': now,
        'ruleId': 1
    }
]

const get = (timerange, keyword, offset, limit) => {
    let lg = [...logs]
    if (timerange) {
        lg = lg.filter(
            item =>
                new Date(item.createdAt) >= new Date(timerange[0]) &&
                new Date(item.createdAt) <= new Date(timerange[1])
        )
    }
    if (keyword) {
        keyword = keyword.toLowerCase()
        lg = lg.filter(
            item =>
                item.transaction.toLowerCase().includes(keyword) ||
                item.ruleName.toLowerCase().includes(keyword) ||
                item.url.toLowerCase().includes(keyword) ||
                item.method.toLowerCase().includes(keyword) ||
                item.status.toString().includes(keyword)
        )
    }
    const count = lg.length
    return {
        data: lg.slice(offset, offset + limit),
        count
    }
}

const clear = () => {
    logs.splice(0, logs.length)
}

const stat = () => {
    throw new Error('Proxy log analysis is temporarily disabled in demo mode.')
}

export default {
    get,
    clear,
    stat
}
